/**
 * User action types
 */

export const LOGIN = 'LOGIN';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const GET_USER_MEDIA = 'GET_USER_MEDIA';
export const GET_USER_MEDIA_SUCCESS = 'GET_USER_MEDIA_SUCCESS';
export const GET_USER_MEDIA_FAILED = 'GET_USER_MEDIA_FAILED';

export const GET_USER_FOLLOWS = 'GET_USER_FOLLOWS';
export const GET_USER_FOLLOWS_SUCCESS = 'GET_USER_FOLLOWS_SUCCESS';
export const GET_USER_FOLLOWS_FAILED = 'GET_USER_FOLLOWS_FAILED';

export const GET_USER_FOLLOWED_BY = 'GET_USER_FOLLOWED_BY';
export const GET_USER_FOLLOWED_BY_SUCCESS = 'GET_USER_FOLLOWED_BY_SUCCESS';
export const GET_USER_FOLLOWED_BY_FAILED = 'GET_USER_FOLLOWED_BY_FAILED';


/**
 * Media action types
 */

export const GET_MEDIA_DETAILS = 'GET_MEDIA_DETAILS';
export const GET_MEDIA_DETAILS_SUCCESS = 'GET_MEDIA_DETAILS_SUCCESS';
export const GET_MEDIA_DETAILS_FAILED = 'GET_MEDIA_DETAILS_FAILED';

export const GET_MEDIA_COMMENTS = 'GET_MEDIA_COMMENTS';
export const GET_MEDIA_COMMENTS_SUCCESS = 'GET_MEDIA_COMMENTS_SUCCESS';
export const GET_MEDIA_COMMENTS_FAILED = 'GET_MEDIA_COMMENTS_FAILED';

export const GET_MEDIA_LIKES = 'GET_MEDIA_LIKES';
export const GET_MEDIA_LIKES_SUCCESS = 'GET_MEDIA_LIKES_SUCCESS';
export const GET_MEDIA_LIKES_FAILED = 'GET_MEDIA_LIKES_FAILED';

export const POST_MEDIA_COMMENT = 'POST_MEDIA_COMMENT';

export const DELETE_MEDIA_COMMENT = 'DELETE_MEDIA_COMMENT';

export const POST_MEDIA_LIKE = 'POST_MEDIA_LIKE';

export const DELETE_MEDIA_LIKE = 'DELETE_MEDIA_LIKE';
